version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t dockerfile:$TAG .
          docker push dockerfile:$TAG